apiVersion: skaffold/v2alpha3
kind: Config
metadata:
  name: skaffolddemo
build:
  local:
   push: true
  tagPolicy: 
    sha256: {}
  artifacts:
  - image: gcr.io/gcpdevopsdemo/demo/skaffold-example
    context: .
    docker:
     dockerfile: deployment/dockerfile
deploy:
  kubectl:
    manifests:
      - deployment/k8s/*.yaml