apiVersion: skaffold/v2beta12
kind: Config
build:
  tagPolicy:
   dateTime:
    format: "2021-02-22"
    timezone: "IST"

  artifacts:
  - image: gcr.io/gcpdevopsdemo/demo/skaffold-example
deploy:
  kubectl:
    manifests:
      - k8s-*