apiVersion: v1
kind: Service
metadata:
  name: demo-service
  namespace: test
  labels:
   app: demo
   env: test
spec:
  ports:
  - name: demoapp1
    port: 80
    protocol: TCP
    targetPort: 80
  - name: demoapp2
    port: 8080
    protocol: TCP
    targetPort: 8080
  selector:
    app: demo