apiVersion: v1
kind: Pod
metadata:
  name: demo
  labels:
    app: demo
    env: test
  namespace: test
spec:
  containers:
  - name: demo-java
    image: gcr.io/gcpdevopsdemo/demo/skaffold-example
    imagePullPolicy: Always
    ports: 
    - containerPort: 80
      name: demoapp1
    - containerPort: 8080
      name: demoapp2